### ISSUE TITLE
actcat client command missing

### ISSUE THREAD

**Issue by ntadej** [ARCControlTower/aCT#76]
The only important client-side command still missing is `actcat`. It should directly replicate `arccat` but use the job information from the database.

I hope this is technically possible.

**Comment by jakobmerljak** [comment]
This should be possible to implement on the local client by using the same job filtering semantics as other client commands and then performing exec into `arccat` with the rest of parameters.

These are parameters that can be implemented without bigger complications:

- `-a`, `-j`, `-i`, `-s` can be covered by the same job filtering parameters as in other client commands

- `-o`, `-e`, `-l`, `-P`, `-t` can be passed directly to `arccat`

Would above parameters be enough? Parameters `-r` and `-c` would require some more work.

**Comment by ntadej** [comment]
To be honest, I'm not familiar with all the flags you listed. For `actcat`, I think it would suffice to
 - handle one job at a time
 - reference the job by arc job ID, internal act job ID or full job name (if unique)

**Comment by jakobmerljak** [comment]
While trying to implement this I found out that `arccat` requires job database (`~/.arc/jobs.dat`). Since aCT client doesn't store jobs in ARC's databases, the `arccat` command complains that there is no job database.

@davidgcameron do you know if it is possible to use `arccat` without a job database and just with the appropriate job ID, proxy (by using X509_USER_PROXY) and cluster (by using --cluster parameter)? According to the man page, this doesn't seem to be possible.

**Comment by davidgcameron** [comment]
I think you could just use arccp to copy the stdout from the job session dir, which does not require the ARC DB. You would need the ARC job ID and the stdout location of the job from the aCT DB and then do something like

`arccp gsiftp://cluster.host/jobid/stdout -`

You could also implement it directly in python using the ARC API instead of spawning a process - see an example at https://source.coderefinery.org/nordugrid/arc/-/blob/master/python/examples/copy_file.py

**Comment by jakobmerljak** [comment]
I implemented the basic functionality by calling `arccp` to copy stdout as advised. `actcat` is available for testing [here](https://github.com/jakobmerljak/aCT/blob/actcat/src/act/client/actcat.py), in branch [actcat](https://github.com/jakobmerljak/aCT/tree/actcat).

I will also add switches for printing stderr, A-REX's error log (`-e` and `-l` in `arccat`, respectively) and arbitrary file from session dir.

**Comment by ntadej** [comment]
Thanks Jakob!

Seems to be working mostly as expected, but it would be nice if one can select job by exact `jobname`. Currently one can just search which causes issues if one job is a substring of another.

**Comment by jakobmerljak** [comment]
I added switch -n/--name that matches `jobname` directly. If there are multiple jobs with the same `jobname` you will still get outputs for multiple jobs.

Additions are available for testing in 3d94bb9af45b8c4c5da428de441718c8b0208bc0 (branch [actcat](https://github.com/jakobmerljak/aCT/tree/actcat) is rebased and force pushed).

**Comment by jakobmerljak** [comment]
Implementation is ready to be merged in #81.
